## Cau hinh ngan luong
#nganluong.merchant_id=69324
#nganluong.merchant_pass=89031b28003ff031e680e39996f3f8d2
#nganluong.receiver_email=huynhnhu.gmeet@gmail.com
#nganluong.api_url=https://www.nganluong.vn/checkout.php

# # Cau hinh database
# db.url=jdbc:sqlserver://localhost:1433;databaseName=QuanLyBanVe
# db.user=sa
# db.password=sapassword

#nganluong.merchant_id=36680
#nganluong.merchant_pass=matkhauketnoi
#nganluong.receiver_email=demo@nganluong.vn
#nganluong.api_url=https://sandbox.nganluong.vn:8088/nl30/checkout.php

## --- CAU VNPAY SANDBOX ---
#vnpay.url=https://sandbox.vnpayment.vn/paymentv2/Payment/Error.html?code=03
#vnpay.tmn_code=XB5KTVQQ
#vnpay.hash_secret=3RSIK32YNBKUZDJBKWVR2SFKLP534YM1
#vnpay.return_url=https://google.com.vn

vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.tmn_code=CGXZLS0Z
vnpay.hash_secret=XNBCJFAKAZQSGTARRLGCHVZWCIOIGSHN
vnpay.return_url=https://nguyen-thi-huynh-nhu.github.io/ve-chung-toi/about-us.html